export const GET_ALL_CONTACT = "GET_ALL_CONTACT";
export const SEARCH_CONTACT = "SEARCH_CONTACT";

export const GET_ALL_CHAT = "GET_ALL_CHAT";
export const SEND_TEXT_MESSAGE = "SEND_TEXT_MESSAGE";
export const CHANGE_USER_CHAT = "CHANGE_USER_CHAT";

export const SHOW_POPUP_TRANSACTION = "SHOW_POPUP_TRANSACTION";
export const SHOW_POPUP_PHONE_CONFIRM='SHOW_POPUP_PHONE_CONFIRM'
export const HIDE_POPUP_TRANSACTION = "HIDE_POPUP_TRANSACTION";

export const SHOW_REVIEW_GIFT_CARD = "SHOW_REVIEW_GIFT_CARD";
export const HIDE_REVIEW_GIFT_CARD = "HIDE_REVIEW_GIFT_CARD";

//======================================================================
export const SHOW_POPUP_OPTIONAL = "SHOW_POPUP_OPTIONAL";
export const HIDE_POPUP_OPTIONAL = "HIDE_POPUP_OPTIONAL";

//======================================================================
export const SEND_SPLIT_CONFIRMATION = "SEND_SPLIT_CONFIRMATION";
export const SEND_PHONE_REQUIRE_CONFIRMATION = "SEND_PHONE_REQUIRE_CONFIRMATION";
export const SEND_USER_REQUIRE_CONFIRMATION='SEND_USER_REQUIRE_CONFIRMATION'
//==========================================================
export const SEND_SUCCESS_CONFIRM = "SEND_SUCCESS_CONFIRM";
export const GIFT_SUCCESS_CONFIRM = "SEND_SUCCESS_CONFIRM";
export const REQUEST_SUCCESS_CONFIRM = "REQUEST_SUCCESS_CONFIRM";
export const SPLIT_SUCCESS_CONFIRM = "SPLIT_SUCCESS_CONFIRM"
//WEEZZIII
export const TOPUP_SUCCESS_CONFIRM='TOPUP_SUCCESS_CONFIRM'
export const BUYCARD_SUCCESS_CONFIRM='BUYCARD_SUCCESS_CONFIRM'
export const PAYBILL_SUCCESS_CONFIRM='PAYBILL_SUCCESS_CONFIRM'
export const TRANSFER_SUCCESS_CONFIRM='TRANSFER_SUCCESS_CONFIRM'

///==============HOME
export const GET_ALL_TRANSACTION_HISTORIES='GET_ALL_TRANSACTION_HISTORIES'
export const CHANGE_TRANSACTION_INFO='CHANGE_TRANSACTION_INFO'
export const GET_ALL_TRANSACTION_HISTORIES_ERROR='GET_ALL_TRANSACTIONHISTORIES_ERROR'
//===============================TRANSACTION WZZI
export const CANCEL_TRANSACTION ='CANCEL_TRANSACTION'